version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: open-router_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open-router_gateway
    # ports:
    #   - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: or_redis
    # ports:
    #   - "6379:6379"

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: open-router_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker
    container_name: open-router_worker
    depends_on:
      - postgres
      - redis

volumes:
  pgdata: