version: '3'

tasks:
  up:
    cmds:
      - docker compose up --build

  down:
    cmds:
      - docker compose down

  logs:
    cmds:
      - docker compose logs -f

  migrate:
    cmds:
      - tern migrate